"""empty message

Revision ID: 000ed35181b9
Revises: 4e088668e121
Create Date: 2024-02-02 11:48:54.887717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '000ed35181b9'
down_revision = '4e088668e121'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_token')
        batch_op.drop_column('token_expiration')
        batch_op.drop_column('token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.VARCHAR(length=32), nullable=True))
        batch_op.add_column(sa.Column('token_expiration', sa.DATETIME(), nullable=True))
        batch_op.create_index('ix_user_token', ['token'], unique=1)

    # ### end Alembic commands ###
