"""empty message

Revision ID: 306a642824bd
Revises: 4b7ef388c57c
Create Date: 2024-02-02 11:53:37.729470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '306a642824bd'
down_revision = '4b7ef388c57c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_expiration', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('token_expiration')

    # ### end Alembic commands ###
