"""empty message

Revision ID: 838b856f4126
Revises: 70fa6b950169
Create Date: 2024-02-02 11:29:42.580949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '838b856f4126'
down_revision = '70fa6b950169'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=25), nullable=False),
    sa.Column('email', sa.String(length=25), nullable=False),
    sa.Column('password', sa.String(length=25), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
